### ISSUE TITLE
extreme voltage values on the /x /y outputs

### ISSUE THREAD

**Issue by phdsg** [almostEric/FrozenWasteland#1]
interesting modules!
had to give them a try and noticed this...
![lisslfo](https://user-images.githubusercontent.com/33329578/35378411-ff7ffb8c-01b2-11e8-8694-f1ecaf7162f6.PNG)

**Comment by almostEric** [comment]
Hi, thanks for noticing this - I had a check for /0, but not for the range it could produce. This has been fixed in latest release. just waiting for the pull request to be approved for it to go live
