### ISSUE TITLE
Mr Blue Sky panel issues

### ISSUE THREAD

**Issue by paulpiko** [almostEric/FrozenWasteland#100]
Rack beta 1
FW Version 2.0.0
Windows 10

The Gain knobs in the column have tooltips referring to Gaim
![image](https://user-images.githubusercontent.com/56526215/143835801-a3888f1c-13d7-4ba3-85e8-4f8ee55b5c09.png)

Band offset values, starting at most CCW, display as 15, -15, -14, ... 14, 15, -17. The tooltip value ranges from -16 to 16.
![image](https://user-images.githubusercontent.com/56526215/143836194-d7ecc588-cff0-457a-b725-dcb1b192c2de.png)
![image](https://user-images.githubusercontent.com/56526215/143836253-eb166705-e6b0-4c89-8793-1cb2c86d63cc.png)

**Comment by almostEric** [comment]
Thanks for catching this. Both issues have been fixed, Ill submit it to the library, but I suspect it will be a while until they get to it
