### ISSUE TITLE
v2: References to custom fonts stored across frames

### ISSUE THREAD

**Issue by cschol** [almostEric/FrozenWasteland#102]
Your plugin stores references to custom fonts across frames. This leads to crashes in the VST when reloading a project.

For example (but there might be others):
```
ProbablyNoteIndianDisplay() {
     font = APP->window->loadFont(asset::plugin(pluginInstance, "res/fonts/DejaVuSansMono.ttf"));
}
```

Please see the following link on how to resolve this issue and re-submit to the Library:
https://vcvrack.com/manual/Migrate2#2-1-Don-t-store-Font-and-Image-references-across-multiple-frames

**Comment by almostEric** [comment]
Hi Chris, no they don't. All my plug-ins that have slugs have had this issue fixed. You are looking at plugin that is not released.

**Comment by cschol** [comment]
Got it. Apologies, we have numerous plugins with font issues and I have been scanning the code for instances like this.

**Comment by cschol** [comment]
Please reopen and fix.

**Comment by almostEric** [comment]
ah, one module had two places that loaded fonts and I only fixed one.

Anyway, fixed now and pushed. I updated the other github comment chain
