### ISSUE TITLE
v2: Mr Blue Sky keeps font reference across frames

### ISSUE THREAD

**Issue by cschol** [almostEric/FrozenWasteland#103]
`Mr Blue Sky` is still crashing the VST. 

```
BandOffsetDisplay() {                                  
   font = APP->window->loadFont(asset::plugin(pluginInstance, "res/fonts/01 Digit.ttf"));
}  
```

`HyperMeasures` also has a problem, but as far as I can see it is not used.

Also, please don't forget to update the version in `plugin.json`. Thanks.

**Comment by almostEric** [comment]
fixed
