### ISSUE TITLE
QAR Groove is not resetting with QAR, causing random grooves on reset

### ISSUE THREAD

**Issue by MaZe6K** [almostEric/FrozenWasteland#104]
When using QAR with the QAR Groove expander, I found that it's shifting the groove when QAR gets reset.
So for example when I have a 4 step groove and delay steps 1 and 2, then reset QAR with a pulse, they end up being steps 2 and 3, or 3 and 4 etc..
It would be nice if they were locked to always represent the same steps, always beginning with step 1.

PS: When loading a new QAR module and Groove expander, step 2 of the Groove expander is moving the start of step 1, so the whole Groove is also already shifted by 1 step when loading fresh.

**Comment by almostEric** [comment]
Not clear what you mean, but have you played with the BEAT button? it  might do what you want

**Comment by MaZe6K** [comment]
The Beat button seems to do exactly what I want to **avoid** :)

I would like to have the same groove each time I restart the sequence, but it changes when I reset and with the Beat button it also changes without resetting.

**Comment by MaZe6K** [comment]
What I would like is that when I send a reset to QAR, the groove expander starts with step 1 on step 1, so that I can always reproduce the same groove and count the steps correctly.

**Comment by almostEric** [comment]
Hi, I understand now. Yeah, QAR can do that. you can either hold down the shift key while the QAR is being reset, or right click and in the context menu choose "Reset to Step 0"

**Comment by MaZe6K** [comment]
Oh ok you're right, with "Reset to Step 0" the groove expander is reacting exactly like I would expect it, thanks!

**Comment by almostEric** [comment]
glad it works! The idea behind the other reset mode is for doing racheting effects
