### ISSUE TITLE
BPM LFO reset strange behavior

### ISSUE THREAD

**Issue by AScustomWorks** [almostEric/FrozenWasteland#11]
Sometimes when receiving a reset signal the LFO speed goes way faster than the clock timing(for four cycles it seems, then it goes back to proper speed). It can be reproduced by sending a couple of reset signals one after another in a quick succession.

**Comment by DomiKamu** [comment]
@AScustomWorks (Alfredo) It's normal, like QuadVCA/Mixer and VCA don't have same initialization settings (you don't have provided a real explanation) :-) :-) :-)

**Comment by AScustomWorks** [comment]
Dominque, we are adults here, so please READ the text, this is a real issue, not a personal opinion.

**Comment by DomiKamu** [comment]
Which text you're meaning exactly? the text just above? (concerning the issue about BPM LFO?). If yes, I totally agree! Having opened an issue about phase issue.

**Comment by almostEric** [comment]
Hi guys, there was a weird behavior with how resets happening faster than the clock could cause weird timing issues. Should be fixed in 0.5.9
