### ISSUE TITLE
QAR Reset Bug

### ISSUE THREAD

**Issue by joozefGlicz** [almostEric/FrozenWasteland#115]
Hi Eric! I would love to use your QAR module because it's exactly what i need, but there is one thing that keeps preventing me from doing it.
More specifically, when I load any project using this module, the "reset to step 0" option always reverts to the default selected state even though it was previously unchecked, which causes the sequencer to delay by one step each time.
If you could fix this little thing it would save me a few projects.
Best regards and thank you for your great work ;)

**Comment by almostEric** [comment]
wish you had submitted this last week :)  as I just pushed an update.
Turns out this was a very simple bug to fix, 
Its been pushed to github, so if you can do your own builds, then you're all set.
Otherwise, you will need to wait until the vcv folks update the library again
