### ISSUE TITLE
FrozenWasteland v0.5.9 (Windows): can compile, but BPM LFO crashes.

### ISSUE THREAD

**Issue by DomiKamu** [almostEric/FrozenWasteland#12]
v0.5.9 Windows

Hi again Eric, and sorry for another issue report here.

I've downloaded 0.5.9 sources via **git clone https://github.com/almostEric/FrozenWasteland.git** (from my /C/Rack/plugins) - dev environment.
Doing **cd FrozenWasteland**, then **make** (or **make dist**) compiles without error/warning message (also without any source alteration).

But when I use dist files (all) for regular (non-dev) VCV Rack 0.5.1, it crashes everytime I open BPM LFO module. No issue about all other modules, however. Where I'm wrong?

Of course, they're all released platforms about 0.5.9 (win, mac, lin) but it simply to understand.

Thanks in advance.
Dominique.

**Comment by DomiKamu** [comment]
Culprit is your MakeFile from current repo, line #14:

SOURCES += $(wildcard src/*.cpp src/filters/*cpp)

must be changed to:

SOURCES += $(wildcard src/*.cpp src/filters/***.cpp**)

missing dot before cpp!

**Comment by almostEric** [comment]
Hi, 
Thanks for noticing this - must have bumped the delete key by accident. Fixed in 0.5.10!
