### ISSUE TITLE
Feature request: Add parameter switch in right click menu

### ISSUE THREAD

**Issue by patman023** [almostEric/FrozenWasteland#14]
Looking to have a momentary hold only, without having to send 2 triggers. is this something that could be added in rightclick menu? (I see the benefit of a latching hold, hence not labeling it a bug).

**Comment by almostEric** [comment]
Hi, 

I like this idea. 

I’m going to start work on porting things to .6 next week, I’ll include this

Eric

**Comment by almostEric** [comment]
This is now available in >= 0.6
