### ISSUE TITLE
0.6.5a - Can't compile on Windows?

### ISSUE THREAD

**Issue by DomiKamu** [almostEric/FrozenWasteland#16]
![image](https://user-images.githubusercontent.com/24851960/39392115-44adb118-4ab0-11e8-9ab9-11bae44b6a12.png)

**Comment by DomiKamu** [comment]
Also 2 warnings concerning unused variables... (before this fatal error).

**Comment by almostEric** [comment]
Hi,

 

Should work now. The unused variable warning I thing were related to missing file (I’m not getting them)

 

Eric

**Comment by DomiKamu** [comment]
Compile is OK, I can close this issue, thanks Eric!
