### ISSUE TITLE
Euclid/Golomb Graphics

### ISSUE THREAD

**Issue by patman023** [almostEric/FrozenWasteland#18]
Win10/Rack 0.6.0/Latest FrW release

Highlighted boxes randomly blink, almost in the same way one might get a random screen tear or artifacting in a video game.

**Comment by lnikj** [comment]
0S X 10.11 & 10.13 / 0.6..

Boxes flashing confirmed.

Not sure if this is connected, as I have not tested this on previous versions, but:  I can only count to 10 on the grid CV inputs. Feeding one, knob at zero, with Vult Knobs, I can only activate 10 steps, not 16.

**Comment by almostEric** [comment]
fixed in v1
