### ISSUE TITLE
licensing of third party code

### ISSUE THREAD

**Issue by squinkylabs** [almostEric/FrozenWasteland#20]
There is a thread on Facebook on the proper way to license third party code. https://www.facebook.com/groups/2035785263299933/permalink/2061753797369746.

**Comment by squinkylabs** [comment]
I believe you agreed at one time to update your documentation so that you would be in compliance with the terms of the software you licence, correct?

**Comment by almostEric** [comment]
yep. It is included in the next update, which has not been pushed to GitHub yet

**Comment by squinkylabs** [comment]
Why was this issue closed? I don't see any third party license verbiage here.

**Comment by almostEric** [comment]
Hi, clearly you want something and I don't know what it is. Can you be more specific what I need to add?

**Comment by squinkylabs** [comment]
Perhaps I missed the information. I would like you to post the required attribution for code that you are re-using. I do it like this: https://github.com/squinkylabs/SquinkyVCV/blob/master/LICENSE-dist.txt
I've run that by Andres and he approves.

If you check out the license on my repo, and most repos for that matter, it requires you to do this.
