### ISSUE TITLE
Build error in branch master

### ISSUE THREAD

**Issue by 573** [almostEric/FrozenWasteland#23]
Ubuntu 16.04
Rack v0.6.1
Plugin git branch master: 

>rack_plugins_1      | g++  -Wsuggest-override -std=c++11 -DTEST -I./eurorack -I./src/dsp-delay -I./src/dsp-filter/utils -I./src/dsp-filter/filters -I./src/dsp-filter/third-party/falco -Wno-unused-local-typedefs -DSLUG=FrozenWasteland -fPIC -I../../include -I../../dep/include -DVERSION=0.6.7 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/HairPick.cpp.o src/HairPick.cpp
rack_plugins_1      | In file included from src/HairPick.cpp:4:0:
rack_plugins_1      | ./src/dsp-delay/ringbuffer.hpp:14:8: error: redefinition of 'struct rack::RingBuffer<T, S>'
rack_plugins_1      |  struct RingBuffer {
rack_plugins_1      |         ^
rack_plugins_1      | In file included from ../../include/dsp/resampler.hpp:7:0,
rack_plugins_1      |                  from ../../include/dsp/samplerate.hpp:2,
rack_plugins_1      |                  from src/HairPick.cpp:2:
rack_plugins_1      | ../../include/dsp/ringbuffer.hpp:14:8: error: previous definition of 'struct rack::RingBuffer<T, S>'
rack_plugins_1      |  struct RingBuffer {
rack_plugins_1      |         ^
rack_plugins_1      | In file included from src/HairPick.cpp:4:0:
rack_plugins_1      | ./src/dsp-delay/ringbuffer.hpp:72:8: error: redefinition of 'struct rack::DoubleRingBuffer<T, S>'
rack_plugins_1      |  struct DoubleRingBuffer {
rack_plugins_1      |         ^
rack_plugins_1      | In file included from ../../include/dsp/resampler.hpp:7:0,
rack_plugins_1      |                  from ../../include/dsp/samplerate.hpp:2,
rack_plugins_1      |                  from src/HairPick.cpp:2:
rack_plugins_1      | ../../include/dsp/ringbuffer.hpp:71:8: error: previous definition of 'struct rack::DoubleRingBuffer<T, S>'
rack_plugins_1      |  struct DoubleRingBuffer {
rack_plugins_1      |         ^
rack_plugins_1      | In file included from src/HairPick.cpp:4:0:
rack_plugins_1      | ./src/dsp-delay/ringbuffer.hpp:296:8: error: redefinition of 'struct rack::AppleRingBuffer<T, S, N>'
rack_plugins_1      |  struct AppleRingBuffer {
rack_plugins_1      |         ^
rack_plugins_1      | In file included from ../../include/dsp/resampler.hpp:7:0,
rack_plugins_1      |                  from ../../include/dsp/samplerate.hpp:2,
rack_plugins_1      |                  from src/HairPick.cpp:2:
rack_plugins_1      | ../../include/dsp/ringbuffer.hpp:140:8: error: previous definition of 'struct rack::AppleRingBuffer<T, S, N>'
rack_plugins_1      |  struct AppleRingBuffer {
rack_plugins_1      |         ^
rack_plugins_1      | ../../compile.mk:64: recipe for target 'build/src/HairPick.cpp.o' failed
rack_plugins_1      | make: *** [build/src/HairPick.cpp.o] Error 1

**Comment by playaspec** [comment]
Same error on OSX:

OSX 10.12.6
Rack v0.6.1
Plugin git branch master:

c++  -std=c++11 -stdlib=libc++ -DTEST -I./eurorack -I./src/dsp-delay -I./src/dsp-filter/utils -I./src/dsp-filter/filters -I./src/dsp-filter/third-party/falco -Wno-unused-local-typedefs -DSLUG=FrozenWasteland -fPIC -I../../include -I../../dep/include -DVERSION=0.6.7 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7 -c -o build/src/HairPick.cpp.o src/HairPick.cpp
In file included from src/HairPick.cpp:4:
./src/dsp-delay/ringbuffer.hpp:14:8: error: redefinition of 'RingBuffer'
struct RingBuffer {
       ^
../../include/dsp/ringbuffer.hpp:14:8: note: previous definition is here
struct RingBuffer {
       ^
In file included from src/HairPick.cpp:4:
./src/dsp-delay/ringbuffer.hpp:72:8: error: redefinition of 'DoubleRingBuffer'
struct DoubleRingBuffer {
       ^
../../include/dsp/ringbuffer.hpp:71:8: note: previous definition is here
struct DoubleRingBuffer {
       ^
In file included from src/HairPick.cpp:4:
./src/dsp-delay/ringbuffer.hpp:296:8: error: redefinition of 'AppleRingBuffer'
struct AppleRingBuffer {
       ^
../../include/dsp/ringbuffer.hpp:140:8: note: previous definition is here
struct AppleRingBuffer {
       ^
3 errors generated.
make: *** [build/src/HairPick.cpp.o] Error 1
