### ISSUE TITLE
Build error in git tag 0.6.7

### ISSUE THREAD

**Issue by 573** [almostEric/FrozenWasteland#24]
Ubuntu 16.04
Rack v0.6.1
Plugin git tag 0.6.7

>rack_plugins_1      | g++  -Wsuggest-override -std=c++11 -DTEST -I./eurorack -I./src/dsp-delay -I./src/dsp-filter/utils -I./src/dsp-filter/filters -I./src/dsp-filter/third-party/falco -Wno-unused-local-typedefs -DSLUG=FrozenWasteland -fPIC -I../../include -I../../dep/include -DVERSION=0.6.7 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/PortlandWeather.cpp.o src/PortlandWeather.cpp
rack_plugins_1      | In file included from src/PortlandWeather.cpp:5:0:
rack_plugins_1      | ./src/dsp-delay/ringbuffer.hpp:14:8: error: redefinition of 'struct rack::RingBuffer<T, S>'
rack_plugins_1      |  struct RingBuffer {
rack_plugins_1      |         ^
rack_plugins_1      | In file included from ../../include/dsp/resampler.hpp:7:0,
rack_plugins_1      |                  from ../../include/dsp/samplerate.hpp:2,
rack_plugins_1      |                  from src/PortlandWeather.cpp:2:
rack_plugins_1      | ../../include/dsp/ringbuffer.hpp:14:8: error: previous definition of 'struct rack::RingBuffer<T, S>'
rack_plugins_1      |  struct RingBuffer {
rack_plugins_1      |         ^
rack_plugins_1      | In file included from src/PortlandWeather.cpp:5:0:
rack_plugins_1      | ./src/dsp-delay/ringbuffer.hpp:72:8: error: redefinition of 'struct rack::DoubleRingBuffer<T, S>'
rack_plugins_1      |  struct DoubleRingBuffer {
rack_plugins_1      |         ^
rack_plugins_1      | In file included from ../../include/dsp/resampler.hpp:7:0,
rack_plugins_1      |                  from ../../include/dsp/samplerate.hpp:2,
rack_plugins_1      |                  from src/PortlandWeather.cpp:2:
rack_plugins_1      | ../../include/dsp/ringbuffer.hpp:71:8: error: previous definition of 'struct rack::DoubleRingBuffer<T, S>'
rack_plugins_1      |  struct DoubleRingBuffer {
rack_plugins_1      |         ^
rack_plugins_1      | In file included from src/PortlandWeather.cpp:5:0:
rack_plugins_1      | ./src/dsp-delay/ringbuffer.hpp:218:8: error: redefinition of 'struct rack::AppleRingBuffer<T, S, N>'
rack_plugins_1      |  struct AppleRingBuffer {
rack_plugins_1      |         ^
rack_plugins_1      | In file included from ../../include/dsp/resampler.hpp:7:0,
rack_plugins_1      |                  from ../../include/dsp/samplerate.hpp:2,
rack_plugins_1      |                  from src/PortlandWeather.cpp:2:
rack_plugins_1      | ../../include/dsp/ringbuffer.hpp:140:8: error: previous definition of 'struct rack::AppleRingBuffer<T, S, N>'
rack_plugins_1      |  struct AppleRingBuffer {
rack_plugins_1      |         ^
rack_plugins_1      | src/PortlandWeather.cpp: In member function 'virtual void PortlandWeather::step()':
rack_plugins_1      | src/PortlandWeather.cpp:265:98: warning: operation on 'in' may be undefined [-Wsequence-point]
rack_plugins_1      |     in = inputs[IN_R_INPUT].active ? in = inputs[IN_R_INPUT].value : in = inputs[IN_L_INPUT].value;   
rack_plugins_1      |                                                                                                   ^
rack_plugins_1      | ../../compile.mk:64: recipe for target 'build/src/PortlandWeather.cpp.o' failed
rack_plugins_1      | make: *** [build/src/PortlandWeather.cpp.o] Error 1

**Comment by Strum** [comment]
I'm getting the same errors trying to build it on slackware linux

**Comment by KlirrFactory** [comment]
Rename all the blaRingBuffer stuff in dsp-delay/ringbuffer.hpp to blaRingBuffer2 ad do the same in the *.cpp that generates the errors (should be two or so).
