### ISSUE TITLE
Implementation issue in Quad Euclidean Rhythm

### ISSUE THREAD

**Issue by philippesalembier** [almostEric/FrozenWasteland#25]
I have noticed a difference between the Euclidean sequences generated by Frozen Wasteland “Quad Euclidean Rhythm” and Southpole “SNS Euclidean Sequencer”. For example, a sequence of length 9 with 6 beats will be:
110101011 in the case of Frozen Wasteland, and
110110110 in the case of Southpole
… the second one seems more “Euclidean” to me.

I posted a comment in the VCV forum wondering whether this was a design choice or an implementation issue in the Frozen Wasteland version. 

Omri Cohen seems to think that this is indeed an implementation error:
      "You are totally right… It’s weird actually because a Euclidean rhythm will be, as you 
        said,  110110110, but I get 101010111
       I guess we should inform the dev."

I am using a Mac and I think Omri is using a PC. So this issue does not seem to be platform specific.

**Comment by almostEric** [comment]
I am guessing there is a rounding error somewhere. will fix this for 1.0

**Comment by almostEric** [comment]
I redid the distribution algorithm in v1. Works much better now
