### ISSUE TITLE
build fail on v1

### ISSUE THREAD

**Issue by davephillips** [almostEric/FrozenWasteland#27]
Fedora 23 Linux
Rack v1.dev.0517cc2

Hi Eric, This error appears to be a repeat of an error I reported and resolved for 0.6.2c but I'm not sure how to fix it for the latest v1:

```
In file included from src/HairPick.cpp:2:0:
./src/dsp-delay/ringbuffer.hpp:4:27: fatal error: util/common.hpp: No such file or directory
compilation terminated.
src/Sabonis.cpp:2:29: fatal error: dsp/decimator.hpp: No such file or directory
compilation terminated.
../../compile.mk:61: recipe for target 'build/src/HairPick.cpp.o' failed
make: *** [build/src/HairPick.cpp.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/PortlandWeather.cpp:2:0:
./src/dsp-delay/ringbuffer.hpp:4:27: fatal error: util/common.hpp: No such file or directory
compilation terminated.
../../compile.mk:61: recipe for target 'build/src/Sabonis.cpp.o' failed
make: *** [build/src/Sabonis.cpp.o] Error 1
../../compile.mk:61: recipe for target 'build/src/PortlandWeather.cpp.o' failed
make: *** [build/src/PortlandWeather.cpp.o] Error 1
```

Any suggestions for a fix ?

**Comment by almostEric** [comment]
It's missing a file that I need to push. I would hold off a but, I am still in the middle of my port to v1 and I haven't built against the *latest* APIs (admittedly they were released a day after I did my pull of vcv)

**Comment by davephillips** [comment]
Thanks for the heads-up, Eric, much appreciated.

**Comment by NielsMayer** [comment]
I too face compilation problems using "VCV Rack v1.dev.26abab6"

See attached file.
[FrozenWasteland.compile.txt](https://github.com/almostEric/FrozenWasteland/files/3199040/FrozenWasteland.compile.txt)

**Comment by almostEric** [comment]
Please read above comment. This is not a released version

**Comment by NielsMayer** [comment]
I saw that. But it is a different error than OP's if you're interested...

**Comment by almostEric** [comment]
Not at the moment 
I am still in the middle of refactoring and hunting down my own bugs.
If you find something after it is released, you can be sure I'll bust my ass fixing it. :)

Thanks! I am slammed at work right now

**Comment by Coirt** [comment]
#28

**Comment by almostEric** [comment]
code moved to master branch. builds in vcv build server
