### ISSUE TITLE
Compile error v1

### ISSUE THREAD

**Issue by SteveRussell33** [almostEric/FrozenWasteland#31]
g++ -std=c++11 -Wsuggest-override -Idep/include -I./src/ui -I./eurorack -I./src/dsp-delay -I./src/dsp-filter/utils -I./src/dsp-filter/filters -I./src/dsp-filter/third-party/falco   -fPIC -I../../include -I../../dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/PortlandWeather.cpp.o src/PortlandWeather.cpp
src/PortlandWeather.cpp:4:10: fatal error: samplerate.h: No such file or directory
    4 | #include "samplerate.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [../../compile.mk:62: build/src/PortlandWeather.cpp.o] Error 1

Building against latest Rack v1 branch

**Comment by almostEric** [comment]
Did you do a make dep first?

**Comment by SteveRussell33** [comment]
Oops yeah forgot that step.
Building master worked
Thx

**Comment by SteveRussell33** [comment]
Found the problem:
res folder not included in makefile

**Comment by almostEric** [comment]
The res folder contains svg images which are not compiled. There is no need for it to be in makefile. 

This already builds on vcv’s build server. There are no build errors

**Comment by SteveRussell33** [comment]
What I meant was the res folder is not included in the DISTRIBUTABLES line in the makefile so a local build doesn't include that folder; which is why the build was successful but the dist doesn't include the svg files.

This is why the brand was appearing in the module browser but not the images and so none of the modules were selectable.

**Comment by almostEric** [comment]
ok, fixed in next push
