### ISSUE TITLE
Portland Weather high CPU in V1

### ISSUE THREAD

**Issue by SteveRussell33** [almostEric/FrozenWasteland#32]
https://drive.google.com/open?id=1vYCt2DniteB827p4lK89t6xodaYGpeNr

**Comment by almostEric** [comment]
Hi Steve,

If you have seen any of my posts you should be aware that portland weather has always used a lot of CPU. right now my goal was just to get it working under v1. I'll try to look at some optimizations later

**Comment by SteveRussell33** [comment]
Ah ok understood.

Thx Eric
Closing
