### ISSUE TITLE
Square out in BPM LFO is wrong

### ISSUE THREAD

**Issue by Petervos2018** [almostEric/FrozenWasteland#35]
Hi Almost Eric,
As the title says the square out from BPM LFO goes from 
+5V to +10V in Unipolar mode and from 
0V to +5V in Bipolar mode.
This should be -5V to +5V in Bi and 0V to +10V in Uni.
BPM LFO 2 is correct !
Version 1.1.0 on Windows.
Thanks for your modules.

Greetings Peter.

**Comment by almostEric** [comment]
good catch. Fixed locally, will be pushed live soon
