### ISSUE TITLE
Quad Alg Rhythm 1.0 -- start inputs not working

### ISSUE THREAD

**Issue by midiguru** [almostEric/FrozenWasteland#37]
My assumption would be that when a pulse (gate or trigger) is received at the Start input jack for a row, the row would jump to its first step and continue from there. In the Windows build of 1.1.0, that isn't happening. When I send a pulse to the Start input jack, nothing happens -- the row just continues stepping along.

**Comment by almostEric** [comment]
Hi,

That is not a good assumption. 
Since QAR does a lot of internal clock manipulation, there needs to be a reference and this is done by measuring the time between the last 2 clock pulses
