### ISSUE TITLE
image rework

### ISSUE THREAD

**Issue by infamedavid** [almostEric/FrozenWasteland#39]
hello  Eric
everybody really like your plugin, FrozenWasteland is killer

it  is hard to say , but I  the image of this plugin is not the best in the rack universe ,  are you open to make some changes to improve the looks of your plugins?

I can make some graphics  proposal if you are agree

Thank you!

**Comment by almostEric** [comment]
Hi,
Like all of my modules, the design is open source, if you want to try improving the look, I'd appreciate the effort. Let me know what you come up with

**Comment by infamedavid** [comment]
nice, I will start to work on it  (based in the components of the res folder)
I ll make a complete proposal from the pannels, knobs, jacks  to the screw

If you have some ideas  let me know and I ll work on that

**Comment by VegaDeftwing** [comment]
![frozen](https://user-images.githubusercontent.com/11283620/80938256-0ebf7900-8d9e-11ea-81e3-f789f53f6f52.png)

vs 

![oldfrozen](https://user-images.githubusercontent.com/11283620/80938267-17b04a80-8d9e-11ea-924f-99e0c78e790f.png)

**Comment by almostEric** [comment]
Hi Vega, Frozen Wasteland's modules are proudly blue! (they are cool, né, frozen after all) and there already a lot of black modules out there.

That said, I really dig the patterns you added to the backgrounds. Can you share?

**Comment by VegaDeftwing** [comment]
Could you add the dark option as alt panels like many other modules already do? 
[res2.zip](https://github.com/almostEric/FrozenWasteland/files/4583534/res2.zip)

These are going to need work. There's so much detail that some cause performance issues.

**Comment by VegaDeftwing** [comment]
Any update on this?

**Comment by almostEric** [comment]
Hi, I played around with this for a while, and as you mentioned it caused serious performance issues even on my fast machine. SVG is just not a good format for these kind of background images unfortunately. For now I have to keep things simple :/

**Comment by VegaDeftwing** [comment]
When I turned the image into a path I didn't put as much effort into optimization as I should have. Like, you'll notice the bottle on Drunken Rampage doesn't cause performance problems like the more detailed images.

If I rework things to solve performance would you still be interested in adding them as alt panels? I also considered maybe making a siloutted frozen icesicle look on each module to keep the 'frozen' aspect- would that be good too?

**Comment by almostEric** [comment]
Hi, I am absolutely interested if you could fix the performance issues. I also want to keep my color scheme since that is part of my brand "identity" :) And I'm not really into alt-panels - I'd like these to be the main ones. It would be cool if the images had "some" relation to the modules' function - for instance, I really liked the image you had of the wristwatch - I thought it seemed more appropriate for the BPM LFO modules since they "keep time, so to speak", but other than that, go nuts!
