### ISSUE TITLE
Discontinuity in the Roulette LFO

### ISSUE THREAD

**Issue by philippesalembier** [almostEric/FrozenWasteland#40]
Hi Eric, 
I enjoy very much your modules. Thanks a lot for your work!

I am observing a discontinuity in the waves generated by the roulette LFO. I attach an image showing the display. As you can see, a straight line is appearing in the display. If I decrease the F value, I see the the curve instantaneously jumps from one extreme of the line to the other extreme. This is not the intended behaviour, right? 
Thanks a lot in advance. 

PD: Just in case, this is helpful, I am using a mac.   

![Screenshot 2019-07-11 at 07 35 44](https://user-images.githubusercontent.com/19853504/61025373-cff4a880-a3b0-11e9-9c69-e1477bd6731e.png)

**Comment by almostEric** [comment]
Hi actually, this is exactly the correct behavior if the ratio of the large circle (Rx) to the small circle (r) is not an even integer. It may look strange on the display, but there are no discontinuities in the outputs.
The upcoming 1.3 update makes controlling the ratio (which is actually more important than each circle's respective size) easier to control
Cheers
Eric

**Comment by philippesalembier** [comment]
Thanks for the feedback. I did not realise this point. It will be indeed good to have direct access to the ratio. Thanks and great job!
