### ISSUE TITLE
Quad Groove Expander: Swing

### ISSUE THREAD

**Issue by midiguru** [almostEric/FrozenWasteland#43]
Had a look at the Quad Groove Expander this afternoon. You have the swing (pulse delay) being added to steps 1, 3, 5, etc. That's backwards. Swing is always a delay in steps 2, 4, 6, etc.

**Comment by almostEric** [comment]
Hi,

Technically swing is just the displacement of a beat/step before or after the rhythm - there are no right or wrong steps to displace.

The groove expander is pretty much just my first test of implementing micro-rhythms and is going to be replaced soon with a more comprehensive module.

The Quad Rhythm expander will let you choose which beats or steps you want to displace and choose the amount of that displacement, though It is going to get overhauled soon too,

Cheers ,
Eric
