### ISSUE TITLE
Hair Pick kills patches

### ISSUE THREAD

**Issue by ContemporaryInsanity** [almostEric/FrozenWasteland#44]
Instantiating Hair Pick V1.6.0 on rack 1.1.3 under linux mint 19.1 immediately consumes 60% & cripples any patch it's added to.

**Comment by almostEric** [comment]
Its, sort of like spinning up 64 delays is resource intensive? Yep. That's what it does. Increase VCV's thread count and you'll be fine

**Comment by ContemporaryInsanity** [comment]
Hmmm, I don't have 0.6.2 installed any more, was sure I didn't have this problem on that version.  Oh well.  Thanks for the great modules Eric.

**Comment by almostEric** [comment]
yeah, the underlying delay sample interpolator got changed on us from .6 to 1.0. At Some point will write my own, but they are a not easy (which is why almost everyone relies on libraries)

**Comment by almostEric** [comment]
and thanks for using them! :)
