### ISSUE TITLE
Rack crashing with String Theory loaded

### ISSUE THREAD

**Issue by spectromas** [almostEric/FrozenWasteland#45]
I loaded up most of the modules after the recent update with the intention of exploring them all together but Rack crashes and tells me to look at the log. This is the relevant part of the log: 

```
[16.132 fatal src/main.cpp:38] Fatal signal 11. Stack trace:
8: /home/alex/.local/opt/Rack/Rack() [0x56d951]
7: /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f4caa427f20]
6: /lib/x86_64-linux-gnu/libc.so.6(+0xbb641) [0x7f4caa4a4641]
5: /home/alex/.Rack/plugins-v1/FrozenWasteland/plugin.so(_ZN12StringTheory7processERKN4rack6engine6Module11ProcessArgsE+0x1026) [0x7f4c8b280a42]
4: /home/alex/.local/opt/Rack/Rack() [0x5b63d1]
3: /home/alex/.local/opt/Rack/Rack(_ZN4rack6engine12EngineWorker3runEv+0x14c) [0x5b781e]
2: /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbd9e0) [0x7f4caae4d9e0]
1: /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f4cac9f86db]
0: /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f4caa50a88f]
```

This is on linux with the latest Rack release.

**Comment by almostEric** [comment]
when did this occur?

**Comment by spectromas** [comment]
In terms of time, just a few hours ago. 
In terms of steps, I added the modules and the crash happened within about 20 seconds. I was not doing anything except looking over the modules (not patching or turning knobs).

**Comment by spectromas** [comment]
I can't reproduce this now after trying in a new patch (I didn't save the one which was crashing) so I will close this issue.
