### ISSUE TITLE
Frozen Wasteland 1.9.1 Wants to Downgrade to 1.9.0

### ISSUE THREAD

**Issue by FunkybotsEvilTwin** [almostEric/FrozenWasteland#46]
Just updated the Frozen Wasteland modules to 1.9.1 but the Library menu option in VCV Rack wants to downgrade the modules to from 1.9.1 down to 1.9.0. Just figured I'd report it in case you weren't already aware.

**Comment by therealkitman** [comment]
That happened to me too. Maybe just a typo in the release numbers?

**Comment by almostEric** [comment]
I am well aware, unfortunately. There is a stupid issue with VCVs screen capture script, so they forced a rollback. 1.9.2 has already been submitted.
