### ISSUE TITLE
Quad Algorhythmic Rhythm: negative modulation of steps locks steps at zero

### ISSUE THREAD

**Issue by Chaircrusher** [almostEric/FrozenWasteland#47]
Randomly modulating steps for a channel of QAR with a negative value (i.e. from a raw sample and hold) will occasionally lock that row into zero steps. To get it to unfroze you have to disconnect the CV input for steps and move the knob.

If a mod value doesn't make sense (negative steps) the simplest solution is to clamp any step mod signal <= 1.0 to 1.0 so there's at least one step. Or (as I do now) use the absolute value of the modulator.  If you were to want to get clever,, let negative step counts make the steps play in reverse order.

But at any rate it seems like steps get stuck at zero with negative modulation values.

**Comment by almostEric** [comment]
Hi, the issue had nothing to do with not clamping values (I think every developer is aware of that function). It is fixed in 1.10
