### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by KarateSnoopy** [almostEric/FrozenWasteland#5]
btw, I made a tutorial on all of your modules here: https://youtu.be/z_bT9Ml6aVU

Feel free to link to in your readme if you want.

**Comment by almostEric** [comment]
That is awesome! I haven't put it in Plugin Manager yet, but there is now a 0.5.7 release. The Quad Euclidean Rhythm has been updated and it is a *monster* now. Tons of new features including the ability to chain multiple QERs by connecting the EOC out of one track into the START input of the next unit. There is Chain Mode button - Boss means it starts running from the start, until a track hits the end of its steps and something is plugged into the Start input, then it waits. Employee mode means it starts up waiting until it gets a start input. So first QER would be boss, the rest Employees, and the last Employee's EOCs get connected back to the Boss's Start (of course you don't *have* to patch it this way :) )

**Comment by KarateSnoopy** [comment]
Nice, thanks for the heads up.  I'll make a follow up tutorial when I get the chance
