### ISSUE TITLE
Damian Lillard labeling.

### ISSUE THREAD

**Issue by therealkitman** [almostEric/FrozenWasteland#50]
Hi,
I may be being pedantic but is the order of the labels "Mid-Hi" and "Mid-Lo" in the SENDS/RETURNS the wrong way around with respect to the location of the three band settings?
![image](https://user-images.githubusercontent.com/14888092/66996940-29811780-f104-11e9-99ef-84cf4967e732.png)
Regards.

**Comment by almostEric** [comment]
yep! Not sure how that happened. will be fixed next release. 

Thanks for catching!
