### ISSUE TITLE
Damien Lillard Reduces Amplitude, Applies Filter

### ISSUE THREAD

**Issue by Miserlou** [almostEric/FrozenWasteland#51]
Hey Eric! Love your modules!

I've been using DL as a band splitter, but I've found that (at least with the default values), it reduces the amplitude of the signal and provides a filtering effect:

<img width="1552" alt="Screen Shot 2019-10-23 at 3 19 18 PM" src="https://user-images.githubusercontent.com/139987/67396884-a13dbf00-f5a8-11e9-8f4d-9859c4df9a19.png">

Any chance you can change defaults so that this doesn't happen? Thanks!

**Comment by almostEric** [comment]
Hi Rich, Looks like there are some phase issues. the low is 90 degrees before and the hi output is 90 degrees ahead. The middle two are ok since the phase offsets cancel each other. 
I'll look into it - there are a few other bugs that need fixing (including the labels on the bands :) )

**Comment by almostEric** [comment]
should be better in 1.10

**Comment by Miserlou** [comment]
Still seeing this in 1.10. :(

<img width="941" alt="Screen Shot 2019-12-30 at 11 28 29 AM" src="https://user-images.githubusercontent.com/139987/71590762-b62e5580-2af7-11ea-9dcf-96d3aba9235c.png">

Can also create some extreme high noise if the high band knob goes past ~7290:
<img width="953" alt="Screen Shot 2019-12-30 at 11 29 37 AM" src="https://user-images.githubusercontent.com/139987/71590786-c8a88f00-2af7-11ea-85c3-6534842b60d3.png">
