### ISSUE TITLE
0.5.7 Quad euclidean crash Rack on Mac

### ISSUE THREAD

**Issue by nay-seven** [almostEric/FrozenWasteland#6]
Hello,
just testing new release, all your plug-ins open ok except quad euclidean , Rack crash directly...
Mac Yosemite here

**Comment by almostEric** [comment]
Hi,

Crap. My friend did the Mac build and he’s been having issues lately (I don’t think he is building against the released version of Rack, but something newer.

 

Can you build from Source?

 

Eric

**Comment by nay-seven** [comment]
hello,
no i can't built myself but i can ask on our French group

**Comment by almostEric** [comment]
Merci! (that is pretty much the limit of my French) 😊
