### ISSUE TITLE
Latest update seems to break QAR in existing patches

### ISSUE THREAD

**Issue by spectromas** [almostEric/FrozenWasteland#61]
Not sure what happened with this, I was playing with my patch and then updated plugins, relaunched Rack and now QAR has forgotten the patterns I had set. This is supposed to sequencing a bass on 2, a kick on 3, and a snare on 4 but as you can see it isn't doing much now. 

![Screenshot_20200516_125501](https://user-images.githubusercontent.com/6443372/82119228-a779cf80-9774-11ea-8c85-fbbf1aa8b662.png)

I just built the 1.12.1-beta tag and the correct patterns are back again: 

![Screenshot_20200516_132528](https://user-images.githubusercontent.com/6443372/82119743-e14cd500-9778-11ea-9ca9-794cb534e01e.png)

**Comment by almostEric** [comment]
Hi,

All the new features (increased beat count, new parameters, new algorithms) required some under the hood reorganizing, so yes, the update probably broke your patch. That said, the same settings will recreate the same beat pattern
