### ISSUE TITLE
Seriously Slow EG v1.14.2 - wrong curves

### ISSUE THREAD

**Issue by therealkitman** [almostEric/FrozenWasteland#65]
Hi,
Just doodling with the SSEG when I noticed that the log and exponential buttons for the DECAY and RELEASE are the wrong way around ie log selects exponential and vise versa. The ATTACK buttons are ok. 

![image](https://user-images.githubusercontent.com/14888092/85357880-ec97db00-b544-11ea-845c-3c0f6cd830af.png)

![image](https://user-images.githubusercontent.com/14888092/85357922-020d0500-b545-11ea-8124-a59a515c26b6.png)

**Comment by almostEric** [comment]
fixed in 1.15
