### ISSUE TITLE
Crash on changing division in Portland Weather

### ISSUE THREAD

**Issue by Chaircrusher** [almostEric/FrozenWasteland#66]
I have a Rack patch that will crash every time you turn the divisions knob on Portland Weather.
[http://cornwarning.com/xfer/Boheln-Pierce-Harry.vcv](http://cornwarning.com/xfer/Boheln-Pierce-Harry.vcv)
Also - if you clock Portland Weather, and the clock is stopped when the patch opens, tweaking the knobs can cause a crash.

Have you tried running your stuff under Valgrind?

**Comment by almostEric** [comment]
divisions has been refactored, so this is no longer an issue
