### ISSUE TITLE
Some Modules crashes the Rack when loading

### ISSUE THREAD

**Issue by FenderBaba** [almostEric/FrozenWasteland#71]
The following Modules crashes the Rack on my machine (i7, Windows 10 Pro 2004 with latest patches) when selected on the library module browser, or if they on a patch file You open:

- Everlasting Glottal Stopper
- Probably Note
- Probably Note - Arabic
- Probably Note - Bohlen Pierce
- Probably Note - Math Nerd
- Portland Weather - Algorithmic Expander
- Quad Algorithmic Rhythm Generator
- String Theory

See the issue list of Valley Audio. He knows more details about a work around from Bogaudio to solve this problem.

Best regards
Remo

**Comment by almostEric** [comment]
Hi, I guess you missed my FB post.

VCV Library is currently having an issue building modules for Windows that use any random number functionality.
That is why I recommend using the v1.15.7 windows release here on this GitHub repository

Cheers
almostEric
