### ISSUE TITLE
update 0.5.7

### ISSUE THREAD

**Issue by Phal-anx** [almostEric/FrozenWasteland#8]
merged you PR before checking it out :( 
the windows version shows 0.5.5 and the new module is missing.. maybe you chose the wrong zip file?

![3456](https://user-images.githubusercontent.com/31989694/35762096-8fa9971a-0891-11e8-8a2a-37acce74c682.png)

**Comment by almostEric** [comment]
Hi, not sure where you are seeing 0.5.5, but it was not a new module. It was an update to the Quad Euclidean Rhythm. I downloaded the binaries from plugin manager and it all looks ok.

**Comment by Phal-anx** [comment]
look at the picture I uploaded ;) it shows 0.5.5
but you are right I didnt see the module.. its in the list LOL ...sry about that!

**Comment by nay-seven** [comment]
A bit Off topic , but the 0.5.7 mac release is ok now, and solves the Euclidean module issue, Thanks !

**Comment by almostEric** [comment]
Where does that version come from? I can see the 0.5.5 as well, but everything is 0.5.7 in my system

**Comment by almostEric** [comment]
nm. even though nothing changed, I resaved all my source code modules, rebuilt and now they all are 0.5.7. win zip file updated
