### ISSUE TITLE
Please make the Div CV Inputs of Gardener usable

### ISSUE THREAD

**Issue by Stubs42** [almostEric/FrozenWasteland#83]
Hi Eric,
Had a use case where I have to use the CV inputs for the div CV inputs.
Recognized that it needs a CV of nearly 10.000V to get a div of 999.
10V just reaches div 2. So I have to use formula modules to multiply the incomming CV by 1000 to make the div inputs usable.
I would really appreciate if when the attenuation of the div cv inputs is fully open that the CV is translated from 0V = 1 to 10V = 999. BTW. How does Gardener treats negative divs given by CV ?

**Comment by almostEric** [comment]
fixed in next update
