### ISSUE TITLE
QAR early onset

### ISSUE THREAD

**Issue by midiguru23** [almostEric/FrozenWasteland#84]
What you'll see in the attached video are three signal channels: (1) QAR playing Trummor. (2) Gate-Seq-64 playing Percussive Vibration. (3) The PCM Drum snare being triggered directly by Clocked. Clocked sends out a Reset on stop, but at the start of the video I click the Reset button manually, so that we'll know things have been reset. (The cables are invisible -- sorry. Clocked Reset goes to both QAR and Gate-Seq.)

QAR does indeed play a pulse immediately when I click Run on Clocked to start the playback -- but it sends that pulse from step 2 (which is empty), NOT from step 1. As a result, all of the devices start together, but from the 2nd quarter-note onwards, QAR is 1/16th ahead, because it started on 2, not on 1. The kick is no longer aligned with the snare and the beep.

As Antonio Tuzzi does in Squonk, the way to fix this (it seems to me) is not to start on step 1 but to start on step 0, which would be the same as the _last_ step.
[early_qua_movie.zip](https://github.com/almostEric/FrozenWasteland/files/6443813/early_qua_movie.zip)

**Comment by almostEric** [comment]
Hi, as mentioned the reset works fine. If you look in documentation you will see there are two modes - a quick reset so you can do ratchetting and a hard reset to step 0.. Currently you need to hold the shift key down to do the hard reset (this works for both key and cv input). In next release I added a menu option to make the cv input default to either method
