### ISSUE TITLE
Seeds of change broken

### ISSUE THREAD

**Issue by Stubs42** [almostEric/FrozenWasteland#86]
After upgrading to the current release, Seeds of change is broken because of 2 serious problems.
Seeds itself only processing the first gate and cv channels, the other 3 gate and cv channels just outputting 0V. The same for the expanders. Only the first (top) output is working. All other channels are not processed. In addition, having 2  expanders (cv or gate) , both generate the same random output, which should be different for every expander. Temporary rolled back to the previous release to keep my patches working and hope those issues will be fixed.
Regards
Dieter

**Comment by almostEric** [comment]
fixed in next release
