### ISSUE TITLE
BPM Clock - Reset not functioning as expected.

### ISSUE THREAD

**Issue by n6smith** [almostEric/FrozenWasteland#9]
There appears to be something amiss with the Reset... If you just connect any cable to it.. no matter what the source... it automatically resets on every pulse of the incoming clock instead of the signal being sent to the reset. It is also affected by the division choosen so an example would be an incoming clock of 120 BPM with a division set to /4 and then connect a cable (Even a null cable) to the reset and watch for how it resets...(Mac Build)

**Comment by almostEric** [comment]
Should be fixed in .0.5.9
