### ISSUE TITLE
question -  Quad Golomb Ruler Rhythm

### ISSUE THREAD

**Issue by S0210** [almostEric/FrozenWasteland#91]
Hello, 
Is  Quad Golomb Ruler Rhythm out of the library? I started re-using VCV after a long break and I don't see this good old device.
Is the old layout still available somewhere or only the Quad Alg. Rhytm is available?
Best regards, Andras

**Comment by almostEric** [comment]
Hi, the QGR and the QER got combined into the far more powerful Quad Algorithmic Rhythm - there you can combine Euclidean, Golumb Ruler, Perfect Balance, Well Formed, Fibonacci and even manual rhythms. 

There is also a whole suite of expanders for the QAR that add some pretty wild capabilities - I encourage you to try them out as well (and one thing to note, the expanders can be chained, so you can use as many as you want).

Cheers!
Eric

**Comment by S0210** [comment]
Thank you, Eric! QAR is clearly a very smart and feature rich plugin. But the UI is too overwhelming for me, I'm afraid. Checking it I see that all knobs are clearly marked and very easy to find everything. The old version could do less but was closer to my simple heart. :) 
Many thanks again! Best regards, Andras

**Comment by almostEric** [comment]
yeah, I don't do simple.
